### ISSUE TITLE
Tooltip rework

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#113]
We want to make the tooltip smart about the data he shows. 
Designs coming soon.

**Comment by miglesiasEB** [comment]
![charts_wip_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/9063187/22848176/615e1678-efa7-11e6-8f88-7852fac15901.png)

![charts_wip_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/9063187/22848180/6dfc7384-efa7-11e6-9d03-800f410ec490.png)

**Comment by Golodhros** [comment]
Let's do #134 first

**Comment by Golodhros** [comment]
We should also improve the show animation on the tooltip, maybe with a fade-in fade-out technique.

**Comment by hisnameisjimmy** [comment]
This would be an excellent solution, the mini-tooltip idea for single source line charts is exactly what I'm looking for. I'm gonna adjust the source files on the build in order to do this on my own, since I don't need multi-line charts.

Another thing, it would be really nice if some of the design could happen in CSS, ie being able to assign your own class to the tooltip and make adjustments through that. Exporting more adjustable parameters would also be nice, right now things like `tooltipWidth` are not useable through config.

**Comment by Golodhros** [comment]
Thanks for the feedback @hisnameisjimmy!

I am curious about your request for a custom CSS class, could you use the standard classes on the tooltip?

Yeah, it will make sense to make the width configurable.

Regarding the output in a container div, you can do that right now. You could listen to the mouse events and do anything you want with that information.

**Comment by Golodhros** [comment]
A bit of work done in https://github.com/britecharts/britecharts/pull/907

**Comment by Golodhros** [comment]
One of the main issues of the Tooltip is that it doesn't listen for the chart height and width, and so it does not have any collision logic to avoid being cut.

**Comment by Golodhros** [comment]
Done in 3.0.0 across #1049, #1050, #1051 and #1052: the tooltip measures the chart it is drawn in and never gets cut off (it flips and slides at the edges), it fades in and out and glides between positions, and `tooltip` and `miniTooltip` are one component with one contract for every chart. The migration guide's step 10 lists the one breaking change. Thanks for the write-up that started this.
