### ISSUE TITLE
Incorrect Demo Code References

### ISSUE THREAD

**Issue by rpheath** [britecharts/britecharts#296]
## The Problem
It seems like the demo code should utilize the same code path(s) that users of Britecharts should use. I noticed, in several areas, that some of the `require(...)` statements are referencing files in the `src` directory when I believe they should be referencing the `umd` directory? Here's [one example](https://github.com/eventbrite/britecharts/blob/master/demos/demo-stacked-area.js#L7).

## Why does this matter?
Someone referencing the demo code might mimic what is shown in the demo (reasonable), but without Webpack bundling the assets, `define()` doesn't exist (which files in `src` are using to create the modules), and errors will pop up. It would be unfortunate for someone trying to work with Britecharts to get hung up on an unrelated error such as that.

Thanks!

**Comment by Golodhros** [comment]
Hi @rpheath, thanks for creating the issue!
I see the problem. I am not sure of the solution though. Those demos have a two-fold utility: they are our docs demos and our sandbox when we need to manually test new changes or features. That's why their dependencies point to the development files, not to the production ready ones (those get updated with every release).

At first, we didn't have the link between the demos and their code, but it was clear that our users wanted a complete example.

The first solution that comes to my mind is separating demos from the sandbox. That would work well, but we would have more code to maintain. What do you think @ryanwholey?

**Comment by Golodhros** [comment]
On version 3 we'll change the way we import the files, hopefully solving this issue.
