### ISSUE TITLE
New Chart: Create force-directed graph 

### ISSUE THREAD

**Issue by vivian-eb** [britecharts/britecharts#335]
## Expected Behavior

Please see attached image. It would be great for visualizing dependencies ... for anything from modules to React components.

![react_components](https://user-images.githubusercontent.com/29084992/29342798-c9594938-81e1-11e7-8b24-76184a0d5bef.gif)

## Current Behavior

Force layout is currently not supported in BriteCharts.

## Context
I would like to create a (stunning) visual of a force-directed graph with the following features if possible:
1) search 
2) tooltip 
3) labels 
4) arrows 
5) pinning/releasing nodes 
6) highlight

This could map everything that takes the shape of a tree/graph. Social/professional circles, project/webpack/React dependencies, and organizational hierarchy.

**Comment by rwholey-eb** [comment]
@evb-sun what do you think!

**Comment by jbrepogmailcom** [comment]
Hello. There has been a great project that allowed dynamical graphs in browser. It is still located here: https://sourceforge.net/projects/touchgraph/

Unfortunately it requires so many authorization confirmations, that it can be used only personally. I can not present it to customers because they would think I want to plant virus in their computers :-(  Have you found anything similar?
