### ISSUE TITLE
Line Chart with Brush fails to redraw line when new data is bound 

### ISSUE THREAD

**Issue by lnufnu** [britecharts/britecharts#417]
When creating line and brush charts, in the brush's `.on(brushExtent)` event, rebinding the chart's data to the line causes the line's axis to be scaled and redrawn, but the lines are not drawn again.

## Expected Behavior
The `drawLines()` method inside line.js should handle entering any selections of the old chart and removing elements.

## Current Behavior
If you follow the documentation, it works because of the hardcoded selectors. If you create a reusable chart, it will redraw the chart's axis with the same lines each time. If you call `d3Selection.selectAll('.line').remove();`, it will remove all lines of any existing charts.

## Steps to Reproduce (for bugs)
Same lines: https://codepen.io/lnufnu/pen/eeYbVK
Working version: https://codepen.io/lnufnu/pen/qVONqZ

**Comment by Golodhros** [comment]
Hi @Inufnu, thanks for the issue!

It looks like a bug!

What do you mean by 'hardcoded selectors'?

**Comment by lnufnu** [comment]
Just that the `d3Selection.selectAll('.brush-chart').remove();` in `redraw charts()` in the demo makes the line chart render both axis and redraw lines. I may be unclear on how the charts interact with each other and how to implement them.

[This codepen](https://codepen.io/lnufnu/pen/eeYbVK) is based on the [line charts demo](https://github.com/eventbrite/britecharts/blob/master/demos/demo-line.js) and isolates it somewhat.

I noticed the brush gradient method applies to multiple instances of a chart on a page too.

**Comment by miglesiasEB** [comment]
Hi @Inufnu,

I have checked the codepen. It seems that the update of the linechart from the brush does not work properly. I think it is because the data-join thinks it is the same data. It's being indexed by topics, and they are the same (only the line's path changes). Note how the tooltip data (dataByDate) is updated properly.

Creating a new linechart after the brushing seems to work, but doesn't seem the ideal solution.

I will move this issue into enhancement. I was thinking on create a 'working with brush' tutorial, and show there different possibilities. This will be a good chance to see what can we do to avoid this. If they were bars with values, I think it won't happen.

Thanks for your help here!

**Comment by lnufnu** [comment]
Hey @miglesiasEB,

Thank you so much for looking into this! I have found a work around for now.

I am keeping `d3Selection.selectAll('.line').remove();` inside my brush function, passing in the selection, and updating the line and tooltip charts from within the brush chart. In my update event listener, I remove the previous brush using `d3.select(brushSelector).selectAll('.brush-chart').remove();`.

[Here is a new pen removing both charts by targeting the DOM elements before updating data.](https://codepen.io/lnufnu/pen/jYqdra)

Thank you for all of your help!
