### ISSUE TITLE
Refactor gridlines logic into a helper file

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#538]
## Expected Behavior

We should have a helper file exposing methods to create and clean the gridlines of some of our charts.
Those are:
- Bar
- Grouped Bar
- Stacked Bar
- Step
- Line 
- Stacked Area

## Current Behavior

We are using duplicated code here and there, making it hard to maintain.

## Next steps
Let's analyze the problem and discuss the desired API

**Comment by bratter** [comment]
I've been thinking about this in context of #527 also. Couple of general thoughts and some specifics for the gridlines.

### General - My 2c :-)
* This and some other things (such as a generalization of the axis in #527) are components just like the d3 axis
* Perhaps it makes sense to divide the library into 3: 
  - Charts: Rendering overall displays
  - Components: Rendering small, modular parts
  - Helpers: Non-rendering utility functions
* In general, the components can all be built like reusable d3 functions just like a full chart

### Gridline Specific Comments
* Gridlines are really just a simplified version of the d3 axis component without labels/path and with the length of the "ticks" controlled by a chart with accessor rather than a tickSize accessor
* Therefore, perhaps could create a gridHorizontal and gridVertical component from d3 axis, plus a grid component that wraps them for 2D grids
* The individual horizontal and vertical grids would take their range from the scale and the length of the gridlines from a lineLength accessor, plus would have ticks, tickFormat, tickValues, tickArguments accessors to keep similar to an axis, but drop tickSize and tickPadding
* The grid component would then have (a) a grid accessor just like the current line chart (with v|h|f options), (b) a width/height to nicely tie into a chart, and (c) an xScale and yScale accessor to set the appropriate scales
* I think this construct is both easy to use if you use the 2D grid, plus super extensible - for instance could drop one into a "briteAxis" component so its easier to link the extended gridlines and axis formatting together

So that's just my 2c... Let me know if that approach is of interest to you.

Cheers!

**Comment by Golodhros** [comment]
Hi @bratter, thanks a lot for your analysis!

I liked your proposed solution of splitting the logic in three. On the same level, I really liked the way they implemented a separation of charts by 'frames' in [Semiotic](https://emeeks.github.io/semiotic/#/semiotic/), I think in that line of thought, the grids would be just part of the frames.

In general, I am aware that in Britecharts as a project, there is plenty of duplication. Not only axis, and gridlines, but we also duplicate logic to create the base SVG and groups, the accessors and some other pieces. This, in the most part has been intentional.

The idea behind Britecharts was two-fold: on one side, we wanted to allow developers and designers with little experience on D3.js to build great interactive charts with little initial effort. On the other hand, we wanted to propose a framework for helping D3.js developers to create new D3.js charts by following standards like the Reusable API and Test Driven Development.

Due to this last goal, I have been always pretty reluctant to create abstractions, delaying them until they were really obvious (and painful not to create them), so any D3 developer would have an easy time forking and customizing our charts.

That said, I think abstracting the gridlines would be great. I would push for a 2 levels abstraction for now. If we manage to keep the helpers focused and self-contained, I think we would have enough flexibility to change our minds later.

In practical terms, this would be just charts and helpers (with some helpers dealing with the DOM and others don't). In my mind, it would be a grid helper that, given the scales, ticks and root SVG, it adds the group element and the grids.

I am not sure if I would expose a method to clean them, or it would be integrated...

**Comment by bratter** [comment]
Thanks for the reply!

Fair enough on the overall strategy piece, although I'm not quite sure how the  'frames' concept applies here - surely any abstraction, be it components, helpers, etc. are all part of the frames and are more a matter of convenience for the library author rather than a consumer. But that's for another time!

As for gridlines specifically, I'm building a helper anyway that will expose a very similar API as d3's chart. Once I'm a bit further progressed, I'll push it to my fork and you can check it out to see if it is vaguely along the lines of what you were thinking for britecharts - and if yes can tweak from there.

Cheers

**Comment by Golodhros** [comment]
Cool! Excited to see what comes from that!!
Thanks a lot @bratter !!

**Comment by bratter** [comment]
I've finished a first pass at the grid helper (still some open questions and no styles or jsdoc). You can see the diff here: https://github.com/eventbrite/britecharts/compare/master...bratter:feat-gridline-helper.

Couple of specifics:
* It exposes three functions: `gridHorizontal`, `gridVertical`, and `grid`
* `gridHorizontal` and `gridVertical` are modelled very closely off `d3.axisLeft` etc. This means that they:
    * Have a very similar API for ticks and scales
    * Deal with all types of scales (continuous, band, etc.) the same way
    * Are transition safe, and animated with the same keyframes as d3 axis' ticks
* `grid` is a wrapper that calls both the H and V variants to make a 2D grid with a simpler API

If it looks good to you, I can do docblocks and styles. Also have some API-related questions:
* **How to manage container elements?** Currently `gridHorizontal` and `gridVertical` make their own containers. This is different from d3.axis and has pros (easier to apply classes and think about selections) and cons (likely will need another wrapper in a chart to manage adding and removing). I leaned toward including wrappers, but...
* **What should the API be for attributes that are shared by the horizontal and vertical grid?** One example is `offsetStart` which governs the projection of the grid line beyond the area defined by the scales. Should this be (a) a single accessor that controls both H and V, (b) a single accessor with an overloaded form allowing H and V to be set separately with an array form, or (c) three separate accessors (offsetStart, offsetStartH, offsetStartV)? (a) is inflexible, (b) is complex, (c) creates a large API (everything 3x...), so not sure which is best.
* **Should these shared attributes be labelled with a suffix of X/Y or H/V (if at all based on the above)?** I can see arguments for both - scales ar more intuitive as X/Y, but offsets as H/V. Maybe consistency isn't necessary?


Cheers,
Brendan

**Comment by Golodhros** [comment]
Hi @bratter, thanks for sharing this branch!

I have been checking the code and congratulations, it is a great piece of work! I loved how you tested it and how clean the code looks, amazing job!

The code is really tight, and that's probably the only problem I have with it. I don't feel I completely understand all of it. Specifically, I don't understand some of the things it does, like:
- Some of the operations you do inside ternaries, like 
```return arguments.length ? (scaleY = _, gridH.scale(scaleY), grid) : scaleY;```
- The concept of context in the gridBase
- Some of the code in the gridBase

Maybe your comments will help in that sense? Would you be open to give us a code walkthrough? I also admit that, as we don't usually use a lot of ternaries, some of its uses bend my mind too much.

Regarding your API questions:
- Yeah, wrappers feel right
- For the shared API, I would tend to go with the more explicit way, so IMO c) will go better with the rest of the library
- I am not sure about the suffix. How would this work when the charts are horizontal vs vertical? Would the grid rotate?

Overall, let me repeat that this is great work! I only have doubts in respect of the complexity of it (mainly if we would be able to fix any bug that came up), the use of ternaries and some other small details.

Thanks a lot for this!

**Comment by bratter** [comment]
Hi @Golodhros, no worries, I learnt a lot doing this as I spent quite a while looking through the core d3 code!

To address a couple of the specifics (which could either be tweaked in code or explained in comments)
* `(scaleY = _, gridH.scale(scaleY), grid)` uses the [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator) - so sets scaleY, sets the scale on the gridH, then returns grid - that is how d3.axis has all their getter/setters, but could easily be broken out into multi-line statements:
```js
if (!arguments.length) return scaleY;
scaleY = _;
gridH.scale(_);
return grid;
```

* Context makes the grid (and axis in d3.axis) transition-safe - i.e. you can call it on either a selection or a transition and works fine in both cases, animating the transition as appropriate. The line`selection = context.selection ? context.selection() : context` sets the selection to either a selection if it were passed or grabs the selection from a transition (context.selection is duck-type checking a transition because a d3 selection doesn't have a selection() method, but transition does). Then the later conditional `if (context !== selection) { ... }` ensures the animation code only runs if it is a transition.
* I'm going to guess that some of the other questions are on the lineExit/Enter callbacks - Bostock et al are geniuses! I eventually worked out what the similar stuff does in d3.axis, and can explain/document if required.
* As for suffixes: I built this with the mindset that they could (and would have to be) handled by a chart implementation in the same way as an axis. This does mean that it requires a decent number of conditionals to allow dynamic orientation switching which would apply to both H/V and X/Y options, although the way d3 does it in axis is pretty slick... Alternatively one could use something not specific to the coordinate system (like Value/Category or Dependent/Independent) but that seems mind-bending. Was thinking that the "value" axis formatting with the offset ticks and extended gridlines that you use in most of the charts can get a helper just like the time axis does in line chart, which means that complexity only needs to be dealt with once.

As for next steps:
* I can reduce the use of ternaries and comma operators
* Add jsdoc and styles
* Do a first pass at the suffixed accessors, although this can be changed later
* Do a PR so you can comment/suggest changes as appropriate to make sure its clear

Make sense?

**Comment by Golodhros** [comment]
Hi @bratter, thanks for your response!

Yeah, it would be great if you could do it in a multiline basis. Also, we usually include curly braces in all our ifs.

Thanks for the explanation of the context, I get it now, it makes a lot of sense!

Yeah, Bostock is a genius! I would love to read more about it. In Britecharts though we prefer less neat code so it is easier for contributors to get started or modify things.

Re: suffixes, it sounds good! I think you have a good grasp of it and will go with what you think is better at this point.

The next steps sound awesome! I want to thank your work on this, you are doing an awesome job!

Thanks!!
