### ISSUE TITLE
Tooltip issues in IE, Microsoft Edge

### ISSUE THREAD

**Issue by flacoman91** [britecharts/britecharts#650]
## Expected Behavior
the information in tooltips in IE are sometimes hanging off of the tooltip. 

## Current Behavior
Depending on how you hover the mouse over a data point, the text sometimes goes off the tooltip.

## Steps to Reproduce (for bugs)
1. Use IE 11 or MS Edge
2. go to https://eventbrite.github.io/britecharts/tutorial-stacked-area.html or https://eventbrite.github.io/britecharts/tutorial-line.html
3. hover over tooltip

## Screenshots (if appropriate):
<img width="821" alt="screen shot 2018-07-31 at 4 09 31 pm" src="https://user-images.githubusercontent.com/1038306/43484869-9c47ddf0-94dd-11e8-9b41-fb66368bc7c4.png">
<img width="869" alt="screen shot 2018-07-31 at 4 07 11 pm" src="https://user-images.githubusercontent.com/1038306/43484878-9f43cd20-94dd-11e8-8837-041ec2811ff0.png">

## Your Environment

* Version used: 2.9.3
* Browser Name and version: Internet Explorer 11, Microsoft Edge
* Operating System and version: Windows 7, Windows 10

**Comment by sagardalvi** [comment]
@Golodhros I am also facing the same issue for a tooltip when I have used a tooltip.valueFormatter() function. 
For some points, tooltip label value gets out of the tooltip boundary, If we slightly move the cursor then it re-renders correctly.

![image](https://user-images.githubusercontent.com/13640403/43707977-eb995a84-9986-11e8-9124-157522c0b8cc.png)

**Comment by DalerAsrorov** [comment]
I don't have access to IE11 in Mac now but I will test it with IE11 tomorrow in a working machine. By looking at the code, there is a fishy line that may cause these issues:
https://github.com/eventbrite/britecharts/blob/master/src/charts/tooltip.js#L363

I tried to find a similar case where `tooltipRight.node().getBBox()` is called and and found a thread that suggests that it may not work well in both IE10 and IE11:
https://stackoverflow.com/questions/16833304/scalable-vector-graphicssvg-getbbox-not-working-in-internet-explorer-10

If I manually put 0 instead of `tooltipRight.node().getBBox().width` in that line mentioned, it shows up like this:
<img width="467" alt="screen shot 2018-08-06 at 2 43 35 am" src="https://user-images.githubusercontent.com/9118852/43709755-892e3cf2-9922-11e8-9865-3fce1706e15c.png">
So I suspect that there is something wrong with calling `getBBox` on the tooltip's right text node.

**Comment by flacoman91** [comment]
I also use a Mac and have been testing using virtualbox and the free images from microsoft: 
 https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I just point the ip address of the host machine (mac) and port :8001 and the demos work.

I will also take a look at this issue since another thing I was working on had issues with getBBox and I had to use .node().getBoundingClientRect().width.

IE and Chrome/Safari/Firefox don't all use the same methods.

**Comment by Golodhros** [comment]
Hi, thanks for looking into this issue!

We did saw this issue time ago in IE11, but after some time looking into it I couldn't come up with a solution. I hope you can!

**Comment by flacoman91** [comment]
I just got my Windows 10 vm running and this is also occurring in Microsoft Edge as well.   going to update the ticket with this info.

**Comment by Golodhros** [comment]
We'll drop IE support.
