### ISSUE TITLE
Line chart with Brush tooltip not showing

### ISSUE THREAD

**Issue by watoo** [britecharts/britecharts#749]
Hi,
Please see this example. the tooltip is not showing up. https://codepen.io/Britecharts/pen/XzOebW

How can I show tooltip in this example.

**Comment by watoo** [comment]
```
.on('customMouseOver', function () {
                        chartTooltip.show();
                    })
```
in above example
` chartTooltip.show` is undefined

**Comment by Golodhros** [comment]
Hi @watoo, thanks for opening this issue!

I checked out and you had some issues with the sequencing of the tooltip. It was undefined because you didn't create the tooltip instance by then, as it was created inside a function below that wasn't actually called.

Also, you need to attach the tooltip to the line only after this has been rendered, as it uses an element within the line to render the tooltip.

A modified CodePen with the fixes is in https://codepen.io/Britecharts/pen/XzOebW?editors=1011

**Comment by watoo** [comment]
Hi, 
in the updated example, the tooltip does not work when we select a range from brush chart. Please check.

**Comment by Golodhros** [comment]
Sorry, I messed up that Codepen and can't go back.
I think it was a similar issue, related to the timing of the creation of the tooltip and the charts
