### ISSUE TITLE
words are truncated along the x-axis(step-chart)

### ISSUE THREAD

**Issue by Tonypz** [britecharts/britecharts#756]
when the container is texed, words are truncated along the x-axis
![Снимок экрана 2019-09-01 в 22 35 12](https://user-images.githubusercontent.com/23166800/64081398-f24bd800-cd08-11e9-987f-703b05e6a5e6.png)

**Comment by Golodhros** [comment]
Hi @Tonypz, thanks for opening this issue!

I think you can avoid this effect by increasing the bottom margin. Let me know if that worked.

**Comment by Tonypz** [comment]
Thanks for the quick response @Golodhros !!!

**Comment by Golodhros** [comment]
I see. Well, mind that when you increase the margin in the bottom, the whole "Y axis" height gets reduced, so you would probably want to increase the height of the chart too.

What I usually recommend in this cases though is to use the horizontal bar chart directly, so that you avoid any labels issue.

**Comment by Tonypz** [comment]
Thank you, I didn’t know. Today I will try.
