### ISSUE TITLE
Add locale to the GroupedBarChart

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#842]
## Expected Behavior

It should have locale support

## Difference from Current Behavior

It doesn't

## Possible Implementation

Copy from other charts

## Context

Consistent API!

**Comment by DalerAsrorov** [comment]
`GroupedBarChart`  has a data shape like this:
```js
[
    {
        name: "2011-01",
        group: "Direct",
        value: 0
    }
]
```
Should 1) the `locale` function be applied to `name` or `value` chart data property? Since the `name` property can be a `Date` data type, the `locale` setter could be applied to it. Or 2) we could simply apply `locale` to the `value` property of the chart data just like in `BarChart`.

**Comment by Golodhros** [comment]
I think the value would make more sense. 
I would assume that the users would pass in the name localized if needed.
