### ISSUE TITLE
Scatterplot tooltip isn't diplayed on the intended position

### ISSUE THREAD

**Issue by shayh** [britecharts/britecharts#923]
## Expected Behavior
tooltip should open next to the mouse pointer

## Current Behavior
a tooltip which opens to the left of a point apeers over it and hide it.

## Possible Solution
this is due to 2 issues, only 1 margin is used to calculate tooltip width and tooltip location is offset by scatter plot left margin.
1. substract both tooltip margins (not only right) from mouseX location to take into account the whole width of the tooltip.
2. add another group on scatter plot, which isn't offset by the graph margin. tooltip container will then be added to that group.

## Steps to Reproduce
use this code in the scatter plot sandbox
`miniTip
	.title('aaaaaaa')
	.valueLabel('x')
chart
	.width(500)
	.height(200)
	.on('customMouseOver', miniTip.show)
	.on('customMouseMove', miniTip.update)
	.on('customMouseOut', miniTip.hide)
	.xAxisFormatType('time')
	.xAxisFormat('%x')
	.xTicks(5)
	.margin({left: 50})`

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/366321/117812186-2a3f4880-b26a-11eb-91dd-04ae8f195a45.png)

## Your Environment
* Britecharts version used: latest
* Browser Name and version: FF
* Operating System and version: Win10

**Comment by Golodhros** [comment]
Fixed in 3.0.0 by #1051. The scatter plot now dispatches the hovered point's own position in the chart's coordinate space (it used to dispatch the pointer in root-svg coordinates into a group that is translated by the margins, which is the offset in the screenshot). The tooltip is anchored to the point and sits beside it, and the browser hover test asserts it never covers the point. Positioning itself was reworked in #1049: the tooltip measures the chart it is drawn in and flips or slides to stay inside it.
